Assignment/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from blog import urls as blog_urls
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', admin.site.urls, name='admin'),
    url(r'^blog/', include(blog_urls, namespace='blog')),
    url(r'^$', RedirectView.as_view(url='/blog/'), name='home'),


    url(r'^accounts/login/$', auth_views.login, {'template_name' : 'accounts/login.html'}, name='login'),
    url(r'^accounts/logout/$', auth_views.logout, {'template_name' : 'accounts/logout.html'}, name='logout'),
]

blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.blogForm, name='form'),
    url(r'^posts/', views.viewPosts, name='posts'),
    url(r'^delete/(\d+)', views.delete_item, name="delete"),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime

class BlogPost (models.Model):
    title = models.CharField(max_length=120, blank=True, null=True)
    description = models.TextField(blank=False)
    timestamp = models.DateTimeField('Time', default=datetime.datetime.now)
    user = models.ForeignKey(User)

    def __str__(self):
        return self.title

blog/forms.py
from django import forms
from .models import BlogPost

class AddBlogPostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ["title", "description"]

blog/views.py
from django.shortcuts import render, HttpResponseRedirect, redirect
from .forms import AddBlogPostForm
from .models import BlogPost
from django.contrib.auth.decorators import login_required

@login_required
def blogForm(request):
    form = AddBlogPostForm(request.POST or None)

    if form.is_valid():
        instance = form.save(commit=False)
        if not instance.title :
            instance.title = 'Untitled Post'
        instance.user = request.user
        instance.save()
        return HttpResponseRedirect('/blog/posts/')

    context = {
        'form': form,
    }

    return render(request, 'blog/form.html', context)

def viewPosts(request):
    list = BlogPost.objects.order_by('-timestamp')
    context = {
        'list': list
    }
    return render(request, 'blog/posts.html', context)

@login_required
def delete_item(request, id):
    instance = BlogPost.objects.get(pk=id)
    if (request.user == instance.user):
        instance.delete()
    return redirect('/blog/posts/')

blog/templates/blog/form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

    <h3>Create a Blog Post</h3>
    <form method="POST" >
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" name="_submit" class="btn btn-primary">Submit</button>
    </form>


{% endblock %}

blog/templates/blog/posts.html
{% extends "base.html" %}

{% block content %}
    <div  id="id_list_table">

        {% for item in list %}

            <div class="demo-card-wide mdl-card mdl-shadow--2dp " >
              <div class="mdl-card__title">
                  <h2 class="panel-title mdl-card__title-text">{{ item.title }} </h2>
              </div>
              <div class="mdl-card__supporting-text panel-body">
                {{ item.description|linebreaks }}
              </div>
              <div class="mdl-card__actions mdl-card--border">
                <a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect">
                    <span class="info">from {{ item.user }} at {{ item.timestamp }}</span>
                </a>
              </div>
              <div class="mdl-card__menu">
                  {% if item.user == request.user %}
                    <a href="{% url 'blog:delete' item.id %}" class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect">
                            <i class="material-icons" > delete </i>
                    </a>
                  {% endif %}
              </div>
            </div>
        <br>
         {% endfor %}
    </div>

{% endblock %}

{% block fab %}
    <a href="{% url 'blog:form' %}">
    <button id="fab" class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored">
      <i class="material-icons">mode_edit</i>
    </button>
        </a>
{% endblock %}

templates/accounts/login.html
{% extends "admin/login.html" %}

{% block branding %}
<h1 id="site-name"><a href="{% url 'home' %}">Welcome to our Blog</a></h1>
{% endblock %}

templates/accounts/logout.html
{% extends "base.html" %}

{% block content %}

		<h2>Logged out</h2>
		<p>Thanks for spending some quality time with the Web site today.</p>
		<p><a href="{% url 'login' %}" class="btn btn-primary btn-lg">Log in again</a></p>

{% endblock %}

templates/base.html
<!DOCTYPE html>

<html lang="en">
<head>
    {% load staticfiles %}
	<link rel="stylesheet" href="{% static 'mdl/material.min.css' %}">
	<script src="{% static 'mdl/material.min.js' %}"></script>
	<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'base.css' %}" rel="stylesheet">
	<link href="{% static 'style.css' %}" rel="stylesheet">
    <title>Blog</title>
</head>
<body>
 <!-- Uses a transparent header that draws on top of the layout's background -->
    <div class="demo-layout-transparent mdl-layout mdl-js-layout">
      <header class="mdl-layout__header mdl-layout__header--transparent">
        <div class="mdl-layout__header-row">
          <!-- Title -->
          <span class="mdl-layout-title">Blog</span>
          <!-- Add spacer, to align navigation to the right -->
          <div class="mdl-layout-spacer"></div>
          <!-- Navigation -->
          <nav class="mdl-navigation">
            <a class="mdl-navigation__link" href="{% url 'blog:form' %}">Form</a>
	        <a class="mdl-navigation__link" href="{% url 'blog:posts' %}">Posts</a>
	        <a class="mdl-navigation__link" href="{% url 'admin:index' %}">Admin</a>
			{% if user.is_authenticated %}
	        <a class="mdl-navigation__link" href="{% url 'logout' %}">Logout</a>
			{% else %}
			<a class="mdl-navigation__link" href="{% url 'login' %}">Login</a>
			{% endif %}
          </nav>
        </div>
      </header>
      <div class="mdl-layout__drawer">
        <span class="mdl-layout-title">Blog</span>
        <nav class="mdl-navigation">
          	<a class="mdl-navigation__link" href="{% url 'blog:form' %}">Form</a>
	        <a class="mdl-navigation__link" href="{% url 'blog:posts' %}">Posts</a>
	        <a class="mdl-navigation__link" href="{% url 'admin:index' %}">Admin</a>
			{% if user.is_authenticated %}
	        <a class="mdl-navigation__link" href="{% url 'logout' %}">Logout</a>
			{% else %}
			<a class="mdl-navigation__link" href="{% url 'login' %}">Login</a>
			{% endif %}
        </nav>
      </div>

          <div class="mdl-grid">

              <div class="mdl-cell mdl-cell--12-col">
                {% block content %}
                {% endblock %}
              </div>

          </div>

    </div>
    {% block fab %}
    {% endblock %}
</body>
</html>